#ifndef __ATMEGA_MODBUS_SLAVE_SETTINGS_H__
#define __ATMEGA_MODBUS_SLAVE_SETTINGS_H__

#define USART_BAUDRATE 9600
#define BAUD_PRESCALER (((F_CPU / (USART_BAUDRATE * 16UL))) - 1)

#define ATMEGA_MODBUS_SLAVE_STATE_UNINIT 0
#define ATMEGA_MODBUS_SLAVE_STATE_WAIT 1
#define ATMEGA_MODBUS_SLAVE_STATE_RECEIVE 2
#define ATMEGA_MODBUS_SLAVE_STATE_PROCESS 3
#define ATMEGA_MODBUS_SLAVE_STATE_TRANSMIT 4

#define ATMEGA_MODBUS_SLAVE_TIMEOUT_RECEIVE 10000;
#define ATMEGA_MODBUS_SLAVE_TIMEOUT_TRANSMIT 1000;

#endif
